/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_session_free: (a: number, b: number) => void;
export const session_connect: (a: number, b: number, c: number, d: number, e: number) => any;
export const session_disconnect: (a: number) => void;
export const session_onEvent: (a: number, b: any) => void;
export const session_peerPublicKey: (a: number) => [number, number];
export const session_privateKey: (a: number) => [number, number];
export const session_reject: (a: number) => any;
export const session_sas: (a: number) => [number, number];
export const session_sendCommand: (a: number, b: any) => [number, number];
export const start: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hfe1c0a6f1e8b05bc: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h16b583695eaaa759: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09422128ca52abe5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__he1a6edec8a7133be: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9768ca95ee41dd2d: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1b7d021b1c5dfc2e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h478ee851fa3c1656: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h080f7a4b92422f09: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h838e0803cc6d1745: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
