/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_session_free: (a: number, b: number) => void;
export const session_connect: (a: number, b: number, c: number, d: number, e: number) => any;
export const session_disconnect: (a: number) => void;
export const session_onEvent: (a: number, b: any) => void;
export const session_peerPublicKey: (a: number) => [number, number];
export const session_privateKey: (a: number) => [number, number];
export const session_reject: (a: number) => any;
export const session_sas: (a: number) => [number, number];
export const session_sendCommand: (a: number, b: any) => [number, number];
export const start: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7489660246e8c56f: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h8e4092050f2e1016: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hba15ed50373f0f9e: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__he5717fda343f3e42: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7e55d1127dc844b4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h491f643b0bd758f9: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb31b9f2fd166600f: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__ha6801afd2ff3851e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h3147e91f33883ca4: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
